// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.vse.togather.domain;

import cz.vse.togather.domain.Group;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Group_Roo_Configurable {
    
    declare @type: Group: @Configurable;
    
}
