// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.vse.togather.domain;

import cz.vse.togather.domain.CategoryEnum;
import cz.vse.togather.domain.Group;
import cz.vse.togather.domain.GroupDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect GroupDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GroupDataOnDemand: @Component;
    
    private Random GroupDataOnDemand.rnd = new SecureRandom();
    
    private List<Group> GroupDataOnDemand.data;
    
    public Group GroupDataOnDemand.getNewTransientGroup(int index) {
        Group obj = new Group();
        setCategory(obj, index);
        setMotto(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void GroupDataOnDemand.setCategory(Group obj, int index) {
        CategoryEnum category = CategoryEnum.class.getEnumConstants()[0];
        obj.setCategory(category);
    }
    
    public void GroupDataOnDemand.setMotto(Group obj, int index) {
        String motto = "motto_" + index;
        if (motto.length() > 500) {
            motto = motto.substring(0, 500);
        }
        obj.setMotto(motto);
    }
    
    public void GroupDataOnDemand.setName(Group obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Group GroupDataOnDemand.getSpecificGroup(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Group obj = data.get(index);
        Long id = obj.getId();
        return Group.findGroup(id);
    }
    
    public Group GroupDataOnDemand.getRandomGroup() {
        init();
        Group obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Group.findGroup(id);
    }
    
    public boolean GroupDataOnDemand.modifyGroup(Group obj) {
        return false;
    }
    
    public void GroupDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Group.findGroupEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Group' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Group>();
        for (int i = 0; i < 10; i++) {
            Group obj = getNewTransientGroup(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
