// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.vse.togather.domain;

import cz.vse.togather.domain.Membership;
import cz.vse.togather.domain.MembershipDataOnDemand;
import cz.vse.togather.domain.MembershipIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MembershipIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MembershipIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MembershipIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MembershipIntegrationTest: @Transactional;
    
    @Autowired
    MembershipDataOnDemand MembershipIntegrationTest.dod;
    
    @Test
    public void MembershipIntegrationTest.testCountMemberships() {
        Assert.assertNotNull("Data on demand for 'Membership' failed to initialize correctly", dod.getRandomMembership());
        long count = Membership.countMemberships();
        Assert.assertTrue("Counter for 'Membership' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MembershipIntegrationTest.testFindMembership() {
        Membership obj = dod.getRandomMembership();
        Assert.assertNotNull("Data on demand for 'Membership' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Membership' failed to provide an identifier", id);
        obj = Membership.findMembership(id);
        Assert.assertNotNull("Find method for 'Membership' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Membership' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MembershipIntegrationTest.testFindAllMemberships() {
        Assert.assertNotNull("Data on demand for 'Membership' failed to initialize correctly", dod.getRandomMembership());
        long count = Membership.countMemberships();
        Assert.assertTrue("Too expensive to perform a find all test for 'Membership', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Membership> result = Membership.findAllMemberships();
        Assert.assertNotNull("Find all method for 'Membership' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Membership' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MembershipIntegrationTest.testFindMembershipEntries() {
        Assert.assertNotNull("Data on demand for 'Membership' failed to initialize correctly", dod.getRandomMembership());
        long count = Membership.countMemberships();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Membership> result = Membership.findMembershipEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Membership' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Membership' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MembershipIntegrationTest.testFlush() {
        Membership obj = dod.getRandomMembership();
        Assert.assertNotNull("Data on demand for 'Membership' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Membership' failed to provide an identifier", id);
        obj = Membership.findMembership(id);
        Assert.assertNotNull("Find method for 'Membership' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMembership(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Membership' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MembershipIntegrationTest.testMergeUpdate() {
        Membership obj = dod.getRandomMembership();
        Assert.assertNotNull("Data on demand for 'Membership' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Membership' failed to provide an identifier", id);
        obj = Membership.findMembership(id);
        boolean modified =  dod.modifyMembership(obj);
        Integer currentVersion = obj.getVersion();
        Membership merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Membership' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MembershipIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Membership' failed to initialize correctly", dod.getRandomMembership());
        Membership obj = dod.getNewTransientMembership(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Membership' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Membership' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Membership' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MembershipIntegrationTest.testRemove() {
        Membership obj = dod.getRandomMembership();
        Assert.assertNotNull("Data on demand for 'Membership' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Membership' failed to provide an identifier", id);
        obj = Membership.findMembership(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Membership' with identifier '" + id + "'", Membership.findMembership(id));
    }
    
}
